model:
  name: baseline_cnn

training:
  loss_fn: BCEWithLogitsLoss
  bce_pos_weight: 4.6
  focal_alpha: 0.25
  focal_gamma: 2.0
  learning_rate: 1e-3
  weight_decay: 1e-4
  warmup_epochs: 5
  max_epochs: 50
  grad_accum: 2
  fbeta_beta: 2

data:
  aug_cfg_path: ./transforms/preprocessing.yaml
  batch_size: 258
  num_workers: 4
