model:
  name: baseline_cnn

training:
  loss_fn: BCEWithLogitsLoss
  bce_pos_weight: 2.0
  focal_alpha: 0.25
  focal_gamma: 2.0
  learning_rate: 0.002
  weight_decay: 0.01
  warmup_epochs: 5
  max_epochs: 10
  grad_accum: 1
  fbeta_beta: 2

data:
  aug_cfg_path: ./transforms/preprocessing.yaml
  batch_size: 128
  num_workers: 4
