model:
  name: efficientnet_b0
  pretrained: true
  freeze_encoder: false
  unfreeze_encoder_blocks: 2
  weights_path: outputs/efficientnet_frozen/best.ckpt

training:
  loss_fn: BCEWithLogitsLoss
  bce_pos_weight: 4.6  # We have 3620 positive samples and 16711 negative samples in the training set
  focal_alpha: 0.25
  focal_gamma: 2.0
  learning_rate: 1e-5
  weight_decay: 1e-4
  warmup_epochs: 5
  max_epochs: 50
  grad_accum: 2
  fbeta_beta: 2

data:
  aug_cfg_path: ./transforms/preprocessing.yaml
  batch_size: 64
  num_workers: 4
