model:
  name: resnet50
  pretrained: true
  freeze_encoder: false
  weights_path: outputs/resnet_frozen/best.ckpt

training:
  loss_fn: BCEWithLogitsLoss
  pos_weight: 4.6  # We have 3620 positive samples and 16711 negative samples in the training set
  learning_rate: 1e-5
  weight_decay: 1e-4
  warmup_epochs: 5
  max_epochs: 50
  grad_accum: 2
  fbeta_beta: 2

data:
  aug_cfg_path: ./transforms/preprocessing.yaml
  batch_size: 256
  num_workers: 4
