model:
  name: efficientnet_b0
  pretrained: true

training:
  loss_fn: BCEWithLogitsLoss
  bce_pos_weight: 2.0
  focal_alpha: 0.25
  focal_gamma: 2.0
  learning_rate: 0.001
  weight_decay: 0.0001
  warmup_epochs: 5
  max_epochs: 10
  grad_accum: 2
  fbeta_beta: 2

data:
  aug_cfg_path: ./transforms/preprocessing.yaml
  batch_size: 64
  num_workers: 4
